export const action = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_USERS: 'GET_USERS',
  CREATE_USER: 'CREATE_USER',
  GET_PRODUCTS: 'GET_PRODUCTS',
  CHECK_AUTH: 'CHECK_AUTH',
  ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART'
}

export const mutator = {
  SET_AUTH: 'SET_AUTH',
  SET_LOADING: 'SET_LOADING',
  SET_PRODUCTS: 'SET_PRODUCTS',
  SET_USER: 'SET_USER',
  SET_USERS: 'SET_USERS',
  SET_PRODUCT_TO_CART: 'SET_PRODUCT_TO_CART'
}

export const get = {
  CURRENT_USER: 'CURRENT_USER',
  IS_AUTHENTICATED: 'IS_AUTHENTICATED',
  LOADING: 'LOADING',
  PRODUCTS: 'PRODUCTS',
  CART: 'CART'
}
