export const action = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_USERS: 'GET_USERS',
  CREATE_USER: 'CREATE_USER',
  GET_PRODUCTS: 'GET_PRODUCTS'
}

export const mutator = {
  SET_USERS: 'SET_USERS',
  SET_USER: 'SET_USER',
  SET_AUTH: 'SET_AUTH',
  SET_PRODUCTS: 'SET_PRODUCTS'
}
