export const action = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_USERS: 'GET_USERS',
  CREATE_USER: 'CREATE_USER',
  GET_PRODUCTS: 'GET_PRODUCTS',
  CHECK_AUTH: 'CHECK_AUTH'
}

export const mutator = {
  SET_USERS: 'SET_USERS',
  SET_USER: 'SET_USER',
  SET_AUTH: 'SET_AUTH',
  SET_PRODUCTS: 'SET_PRODUCTS'
}

export const get = {
  CURRENT_USER: 'CURRENT_USER',
  IS_AUTHENTICATED: 'IS_AUTHENTICATED'
}
